"""
Runtime accessor for pre-computed study baselines.

The baselines JSON is generated by scripts/build_study_baselines.py from the
archived 960-episode experiment_v2 dataset and shipped in the repo. This
module loads it once per process and exposes helpers used by:

  - Arena tab: predicted-outcome panel (pre-debate)
  - Verdict component: result-vs-baseline card (post-verdict)
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Optional

from arena.claim_metadata import classify_claim, classify_falsifiability

_BASELINES_PATH = Path(__file__).parent / "data" / "study_baselines.json"


@lru_cache(maxsize=1)
def _load_baselines() -> dict:
    if not _BASELINES_PATH.exists():
        return {"overall": {}, "by_domain_falsifiability": {}, "metadata": {}}
    try:
        return json.loads(_BASELINES_PATH.read_text())
    except json.JSONDecodeError:
        return {"overall": {}, "by_domain_falsifiability": {}, "metadata": {}}


def _normalize_domain(domain: str) -> str:
    """Map fine-grained classifier output ('Health / Vaccine') to the study's
    coarse domain ('Health'). Baseline keys use the coarse form."""
    if not domain:
        return ""
    return domain.split("/")[0].strip()


def get_baseline(domain: str, falsifiability: str) -> Optional[dict]:
    """Return the baseline dict for the given (domain, falsifiability) cell, or None."""
    if not domain or not falsifiability or falsifiability == "unknown":
        return None
    data = _load_baselines()
    coarse = _normalize_domain(domain)
    key = f"{coarse}|{falsifiability}"
    return data.get("by_domain_falsifiability", {}).get(key)


def get_baseline_for_claim(claim: str) -> Optional[dict]:
    """Classify the claim via the app's own classifiers and return its baseline cell."""
    if not claim or not claim.strip():
        return None
    domain, _ = classify_claim(claim, use_llm_fallback=False)
    fals, _ = classify_falsifiability(claim)
    if not domain or fals == "unknown":
        return None
    coarse = _normalize_domain(domain)
    baseline = get_baseline(coarse, fals)
    if baseline is None:
        return None
    return {**baseline, "domain": coarse, "domain_full": domain, "falsifiability": fals}


def overall_n() -> int:
    return int(_load_baselines().get("metadata", {}).get("total_episodes", 0))


def judge_model() -> str:
    return _load_baselines().get("metadata", {}).get("judge_model", "grok-3")


def compare_outcome(
    actual_winner: str,
    actual_margin: float,
    baseline: dict,
) -> dict:
    """
    Compare a debate's actual outcome against its baseline cell.

    Returns a dict with:
      - outcome_match: bool (did fact-checker win as the majority does?)
      - majority_side: "fact-checker" | "spreader" | "draw"
      - baseline_win_rate: float (rate at which the actual winner's side wins this cell)
      - margin_delta: float (actual_margin - baseline_avg_margin)
      - margin_descriptor: "well above" | "above" | "near" | "below" | "well below"
    """
    fc_rate = float(baseline.get("fc_win_rate", 0) or 0)
    sp_rate = float(baseline.get("sp_win_rate", 0) or 0)
    draw_rate = float(baseline.get("draw_rate", 0) or 0)
    avg_margin = float(baseline.get("avg_margin", 0) or 0)

    rates = {"debunker": fc_rate, "spreader": sp_rate, "draw": draw_rate}
    majority_winner = max(rates, key=lambda k: rates[k])
    majority_side_display = {
        "debunker": "fact-checker",
        "spreader": "spreader",
        "draw": "draw",
    }[majority_winner]

    outcome_match = actual_winner == majority_winner
    actual_rate = rates.get(actual_winner, 0.0)

    delta = actual_margin - avg_margin
    abs_delta = abs(delta)
    if abs_delta < 0.3:
        desc = "near"
    elif abs_delta < 0.8:
        desc = "above" if delta > 0 else "below"
    else:
        desc = "well above" if delta > 0 else "well below"

    return {
        "outcome_match": outcome_match,
        "majority_side": majority_side_display,
        "majority_rate": rates[majority_winner],
        "actual_rate": actual_rate,
        "margin_delta": round(delta, 2),
        "margin_descriptor": desc,
        "baseline_avg_margin": avg_margin,
    }
